
services:
  duckdb:
    container_name: duckdb
    build:
      context: ./docker/duckdb  # Path to DuckDB Dockerfile
    volumes:
      - ./raw_data:/app/data  # Mount raw_data directory for persistent storage
    stdin_open: true
    tty: true
    #networks:
    #  - data_network

