version: "3.9"
services:
  airflow:
    build:
      context: ./docker
      dockerfile: Dockerfile-airflow
    image: custom-airflow:latest
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - oracle
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - airflow-net

  airflow-webserver:
    build: .
    image: airflow-webserver
    container_name: airflow-webserver
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - airflow
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - airflow-net
    command: ["airflow", "webserver"]

  airflow-scheduler:
    build: .
    image: airflow-with-duckdb
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres
      - airflow
    networks:
      - airflow-net
    command: ["airflow", "scheduler"]

  airflow-init:
    build: .
    image: airflow-init
    container_name: airflow-init
    command: ["airflow", "db", "init"]
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    depends_on:
      - postgres
    networks:
      - airflow-net

  dbt:
    build:
      context: ./docker
      dockerfile: Dockerfile-dbt
    container_name: data_engineering_project_dbt
    volumes:
      - ./dbt:/dbt
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_script:/docker-entrypoint-initdb.d  # Mount init_scripts directory to PostgreSQL's init directory

  oracle:
    image: oracleinanutshell/oracle-xe-11g
    container_name: data_engineering_project_oracle
    environment:
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/u01/app/oracle

  duckdb:
    image: python:3.9-slim
    container_name: duckdb
    volumes:
      - ./data:/data
    command: "tail -f /dev/null"

volumes:
  postgres_data:
  oracle_data:
  
networks:
  airflow-net:
    driver: bridge
