dbt_project:
  outputs:
    dev:
      dbname: raw_data
      host: postgres
      pass: airflow
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: airflow
  target: dev
