dbt_project:
  outputs:
    postgres_source:  # Connect to PostgreSQL for raw data extraction
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      dbname: raw_data
      port: 5432
      schema: public

    duckdb_target:  # Connect to DuckDB for staging raw data
      type: duckdb
      path: /app/data/raw_data.duckdb  # Location of DuckDB file for staging
      schema: staging  # Logical schema for staging tables in DuckDB

  target: postgres_source # ??? might change
